In [1]:
from main import *

In [2]:
scores_10 = run_dimension(6, 10, calculate_scores=True)

Loading saved data...
Data loaded in: 30.838003635406494 seconds
Loading saved embedding...
Embedding loaded in: 4.6617701053619385 seconds


100%|█████████████████████████████████████████| 5/5 [1:16:07<00:00, 913.55s/it]


Scores calculated in 4679.7920043468475 seconds
HDBSCAN does not classify 18358 samples


In [3]:
scores_30 = run_dimension(6, 30, calculate_scores=True)

Loading saved data...
Data loaded in: 31.25040030479431 seconds
Loading saved embedding...
Embedding loaded in: 6.618157863616943 seconds


100%|█████████████████████████████████████████| 5/5 [1:18:02<00:00, 936.55s/it]


Scores calculated in 4796.5376608371735 seconds
HDBSCAN does not classify 18358 samples


In [4]:
scores_50 = run_dimension(6, 50, calculate_scores=True)

Loading saved data...
Data loaded in: 31.584598302841187 seconds
Loading saved embedding...
Embedding loaded in: 7.01235556602478 seconds


100%|█████████████████████████████████████████| 5/5 [1:18:27<00:00, 941.47s/it]


Scores calculated in 4821.3529007434845 seconds
HDBSCAN does not classify 18358 samples


In [7]:
li = np.array([scores_10, scores_30, scores_50])

In [8]:
li[:,0]

array([0.38646426, 0.3886443 , 0.38451235])

In [11]:
li[:,1]

array([1.63335846, 1.63335846, 1.63335846])

In [12]:
li[:,2]

array([0.00923312, 0.0086932 , 0.00901025])