In [1]:
from main import *

In [2]:
scores_1_1000 = run_dimension(6, min_samples=1, min_cluster_size=1000, scores=True)

Loading saved data...
Data loaded in: 34.09158372879028 seconds
Loading saved embedding...
Embedding loaded in: 5.49616551399231 seconds
Clustering embedding...
Embedding clustered in: 555.8106393814087 seconds
Saving embedding cluster labels...
Embedding cluster labels saved in: 4.456371545791626 seconds


100%|███████████████████████████████████████████| 5/5 [36:20<00:00, 436.09s/it]


Scores calculated in 2292.700718641281 seconds


In [3]:
scores_10_1000 = run_dimension(6, min_samples=10, min_cluster_size=1000, scores=True)

Loading saved data...
Data loaded in: 31.18600106239319 seconds
Loading saved embedding...
Embedding loaded in: 3.4103784561157227 seconds
Clustering embedding...
Embedding clustered in: 480.4229226112366 seconds
Saving embedding cluster labels...
Embedding cluster labels saved in: 4.477371692657471 seconds


100%|███████████████████████████████████████████| 5/5 [36:21<00:00, 436.34s/it]


Scores calculated in 2295.307102203369 seconds


In [4]:
scores_100_1000 = run_dimension(6, min_samples=20, min_cluster_size=1000, scores=True)

Loading saved data...
Data loaded in: 31.677399158477783 seconds
Loading saved embedding...
Embedding loaded in: 3.289579391479492 seconds
Clustering embedding...
Embedding clustered in: 465.5650177001953 seconds
Saving embedding cluster labels...
Embedding cluster labels saved in: 4.576971054077148 seconds


100%|███████████████████████████████████████████| 5/5 [37:55<00:00, 455.13s/it]


Scores calculated in 2389.092899799347 seconds


In [5]:
scores_1000_1000 = run_dimension(6, min_samples=30, min_cluster_size=1000, scores=True)

Loading saved data...
Data loaded in: 31.697797536849976 seconds
Loading saved embedding...
Embedding loaded in: 3.425978660583496 seconds


100%|███████████████████████████████████████████| 5/5 [38:26<00:00, 461.33s/it]


Scores calculated in 2420.5664989948273 seconds


In [6]:
scores_400_1000 = run_dimension(6, min_samples=40, min_cluster_size=1000, scores=True)

Loading saved data...
Data loaded in: 31.842196464538574 seconds
Loading saved embedding...
Embedding loaded in: 3.3429787158966064 seconds
Clustering embedding...
Embedding clustered in: 469.453994512558 seconds
Saving embedding cluster labels...
Embedding cluster labels saved in: 4.522771120071411 seconds


100%|███████████████████████████████████████████| 5/5 [37:44<00:00, 452.82s/it]


Scores calculated in 2377.7437727451324 seconds


In [13]:
scores_15_1000 = run_dimension(6, min_samples=15, min_cluster_size=1000, scores=True)

Loading saved data...
Data loaded in: 31.989396572113037 seconds
Loading saved embedding...
Embedding loaded in: 3.4905779361724854 seconds
Clustering embedding...
Embedding clustered in: 467.4492073059082 seconds
Saving embedding cluster labels...
Embedding cluster labels saved in: 4.4975714683532715 seconds


100%|███████████████████████████████████████████| 5/5 [38:11<00:00, 458.37s/it]


Scores calculated in 2406.130792617798 seconds


In [14]:
li = np.array([scores_1_1000, scores_10_1000, scores_15_1000, scores_100_1000, scores_1000_1000,scores_400_1000])

In [15]:
li[:,0]

array([0.38612253, 0.38841607, 0.38484877, 0.38500874, 0.38534589,
       0.38476213])

In [16]:
li[:,1]

array([1.50429441, 1.50040956, 1.53566439, 1.61710129, 1.62822221,
       1.60809365])

In [17]:
li[:,2]

array([0.00931573, 0.00942447, 0.00961683, 0.0098779 , 0.00981667,
       0.00966469])

In [11]:
# min_cluster_size_list = np.arange(100,10100,250)

In [12]:
# shapes = []
# for size in tqdm(min_cluster_size_list):
#     result = run_dimension(6, min_samples=30, min_cluster_size=int(size), frames=True)
#     shapes.append(result.shape[0]/2)

In [18]:
scores_10_1000 = run_dimension(6, min_samples=10, min_cluster_size=1000, scores=True)

Loading saved data...
Data loaded in: 32.98042345046997 seconds
Loading saved embedding...
Embedding loaded in: 3.400779962539673 seconds


100%|███████████████████████████████████████████| 5/5 [37:44<00:00, 452.83s/it]


Scores calculated in 2378.783894300461 seconds


In [19]:
scores_11_1000 = run_dimension(6, min_samples=11, min_cluster_size=1000, scores=True)

Loading saved data...
Data loaded in: 34.10662889480591 seconds
Loading saved embedding...
Embedding loaded in: 3.449577808380127 seconds
Clustering embedding...
Embedding clustered in: 477.90698051452637 seconds
Saving embedding cluster labels...
Embedding cluster labels saved in: 4.594971656799316 seconds


100%|███████████████████████████████████████████| 5/5 [37:38<00:00, 451.78s/it]


Scores calculated in 2373.8495604991913 seconds


In [20]:
scores_12_1000 = run_dimension(6, min_samples=12, min_cluster_size=1000, scores=True)

Loading saved data...
Data loaded in: 32.06639552116394 seconds
Loading saved embedding...
Embedding loaded in: 3.3399789333343506 seconds
Clustering embedding...
Embedding clustered in: 474.84677052497864 seconds
Saving embedding cluster labels...
Embedding cluster labels saved in: 4.482571363449097 seconds


100%|███████████████████████████████████████████| 5/5 [38:07<00:00, 457.55s/it]


Scores calculated in 2402.009056329727 seconds


In [21]:
scores_13_1000 = run_dimension(6, min_samples=13, min_cluster_size=1000, scores=True)

Loading saved data...
Data loaded in: 33.587385416030884 seconds
Loading saved embedding...
Embedding loaded in: 3.612177610397339 seconds
Clustering embedding...
Embedding clustered in: 500.205379486084 seconds
Saving embedding cluster labels...
Embedding cluster labels saved in: 4.607770681381226 seconds


100%|███████████████████████████████████████████| 5/5 [39:02<00:00, 468.42s/it]


Scores calculated in 2460.674516916275 seconds


In [22]:
scores_14_1000 = run_dimension(6, min_samples=14, min_cluster_size=1000, scores=True)

Loading saved data...
Data loaded in: 33.901792764663696 seconds
Loading saved embedding...
Embedding loaded in: 3.655378818511963 seconds
Clustering embedding...
Embedding clustered in: 499.5161747932434 seconds
Saving embedding cluster labels...
Embedding cluster labels saved in: 4.77153754234314 seconds


100%|███████████████████████████████████████████| 5/5 [38:50<00:00, 466.08s/it]


Scores calculated in 2449.13808965683 seconds


In [23]:
scores_15_1000 = run_dimension(6, min_samples=15, min_cluster_size=1000, scores=True)

Loading saved data...
Data loaded in: 33.73378562927246 seconds
Loading saved embedding...
Embedding loaded in: 3.684577226638794 seconds


100%|███████████████████████████████████████████| 5/5 [38:47<00:00, 465.54s/it]


Scores calculated in 2446.1773359775543 seconds


In [24]:
li = np.array([scores_10_1000, scores_11_1000, scores_12_1000, scores_13_1000, scores_14_1000, scores_15_1000])

In [25]:
li[:,0]

array([0.3920436 , 0.39445895, 0.387932  , 0.38211347, 0.38994685,
       0.39074388])

In [26]:
li[:,1]

array([1.50040956, 1.57878491, 1.61505475, 1.62085639, 1.52398947,
       1.53566439])

In [27]:
li[:,2]

array([0.00810991, 0.00948163, 0.00846244, 0.00941988, 0.0095641 ,
       0.00987024])